package de.diskostu.spoolstack

class InitialColors {
    companion object {
        val initialColors = mapOf(
            "#000000" to mapOf("en" to "Black", "de" to "Schwarz"),
            "#FFFFFF" to mapOf("en" to "White", "de" to "Weiß"),
            "#FF0000" to mapOf("en" to "Red", "de" to "Rot"),
            "#00FF00" to mapOf("en" to "Green", "de" to "Grün"),
            "#0000FF" to mapOf("en" to "Blue", "de" to "Blau"),
            "#FFFF00" to mapOf("en" to "Yellow", "de" to "Gelb"),
            "#FFA500" to mapOf("en" to "Orange", "de" to "Orange"),
            "#800080" to mapOf("en" to "Purple", "de" to "Lila"),
            "#FFC0CB" to mapOf("en" to "Pink", "de" to "Rosa"),
            "#A52A2A" to mapOf("en" to "Brown", "de" to "Braun"),
            "#808080" to mapOf("en" to "Grey", "de" to "Grau"),
            "#C0C0C0" to mapOf("en" to "Silver", "de" to "Silber"),
            "#FFD700" to mapOf("en" to "Gold", "de" to "Gold"),
            "#40E0D0" to mapOf("en" to "Turquoise", "de" to "Türkis"),

            "#00FFFF" to mapOf("en" to "Cyan", "de" to "Cyan"),
            "#8B4513" to mapOf("en" to "Copper", "de" to "Kupfer"),
            "#B22222" to mapOf("en" to "Brick Red", "de" to "Ziegelrot"),
            "#DC143C" to mapOf("en" to "Crimson", "de" to "Karmesinrot"),
            "#FF1493" to mapOf("en" to "Fuchsia", "de" to "Fuchsia"),
            "#7FFF00" to mapOf("en" to "Lime Green", "de" to "Limettengrün"),
            "#2E8B57" to mapOf("en" to "Forest Green", "de" to "Waldgrün"),
            "#4682B4" to mapOf("en" to "Steel Blue", "de" to "Stahlblau"),
            "#5F9EA0" to mapOf("en" to "Cadet Blue", "de" to "Kadettenblau"),
            "#D2691E" to mapOf("en" to "Chocolate", "de" to "Schokolade"),
            "#FF4500" to mapOf("en" to "Fire Orange", "de" to "Feuerorange"),
            "#DA70D6" to mapOf("en" to "Orchid", "de" to "Orchidee"),
            "#BA55D3" to mapOf("en" to "Medium Orchid", "de" to "Mittlere Orchidee"),
            "#9932CC" to mapOf("en" to "Dark Orchid", "de" to "Dunkle Orchidee"),
            "#4B0082" to mapOf("en" to "Indigo", "de" to "Indigo"),

            "#F0E68C" to mapOf("en" to "Khaki", "de" to "Khaki"),
            "#E6E6FA" to mapOf("en" to "Lavender", "de" to "Lavendel"),
            "#F5DEB3" to mapOf("en" to "Wheat", "de" to "Weizen"),
            "#FFB6C1" to mapOf("en" to "Light Pink", "de" to "Hellrosa"),
            "#87CEEB" to mapOf("en" to "Sky Blue", "de" to "Himmelblau"),
            "#6A5ACD" to mapOf("en" to "Slate Blue", "de" to "Schieferblau"),
            "#708090" to mapOf("en" to "Slate Gray", "de" to "Schiefergrau"),
            "#9ACD32" to mapOf("en" to "Yellow Green", "de" to "Gelbgrün"),
            "#FF69B4" to mapOf("en" to "Hot Pink", "de" to "Knallpink"),
            "#CD5C5C" to mapOf("en" to "Indian Red", "de" to "Indischrot"),
            "#4CAF50" to mapOf("en" to "Mint Green", "de" to "Minzgrün"),
            "#00CED1" to mapOf("en" to "Dark Turquoise", "de" to "Dunkeltürkis"),
            "#8FBC8F" to mapOf("en" to "Dark Sea Green", "de" to "Dunkelmeergrün"),
            "#FF6347" to mapOf("en" to "Tomato", "de" to "Tomate"),
            "#FFDAB9" to mapOf("en" to "Peach", "de" to "Pfirsich"),

            "#FFFACD" to mapOf("en" to "Lemon Chiffon", "de" to "Zitronen-Chiffon"),
            "#E0FFFF" to mapOf("en" to "Light Cyan", "de" to "Hellcyan"),
            "#7B68EE" to mapOf("en" to "Medium Slate Blue", "de" to "Mittleres Schieferblau"),
            "#00FA9A" to mapOf("en" to "Medium Spring Green", "de" to "Mittleres Frühlingsgrün"),
            "#48D1CC" to mapOf("en" to "Medium Turquoise", "de" to "Mitteltürkis"),
            "#191970" to mapOf("en" to "Midnight Blue", "de" to "Mitternachtsblau"),
            "#FFE4E1" to mapOf("en" to "Misty Rose", "de" to "Nebelrosa"),
            "#FFEBCD" to mapOf("en" to "Blanched Almond", "de" to "Gebleichtes Mandel"),
            "#8B008B" to mapOf("en" to "Dark Magenta", "de" to "Dunkles Magenta"),
            "#556B2F" to mapOf("en" to "Dark Olive Green", "de" to "Dunkles Olivgrün"),

            "#B8860B" to mapOf("en" to "Dark Goldenrod", "de" to "Dunkles Goldrute"),
            "#A9A9A9" to mapOf("en" to "Dark Gray", "de" to "Dunkelgrau"),
            "#9932CC" to mapOf("en" to "Dark Violet", "de" to "Dunkleviolett"),
            "#8B0000" to mapOf("en" to "Dark Red", "de" to "Dunkelrot"),
            "#E9967A" to mapOf("en" to "Dark Salmon", "de" to "Dunkler Lachs"),
            "#8FBC8F" to mapOf("en" to "Dark Sea Green", "de" to "Dunkelmeergrün"),
            "#2F4F4F" to mapOf("en" to "Dark Slate Gray", "de" to "Dunkler Schiefergrau"),
            "#00FF7F" to mapOf("en" to "Spring Green", "de" to "Frühlingsgrün"),

            "#FF00FF" to mapOf("en" to "Magenta", "de" to "Magenta"),
            "#DDA0DD" to mapOf("en" to "Plum", "de" to "Pflaume"),
            "#DAA520" to mapOf("en" to "Goldenrod", "de" to "Goldrute"),
            "#FFE4B5" to mapOf("en" to "Moccasin", "de" to "Mokassin"),
            "#F0FFFF" to mapOf("en" to "Azure", "de" to "Azur"),
            "#F5F5DC" to mapOf("en" to "Beige", "de" to "Beige"),
            "#FFF5EE" to mapOf("en" to "Seashell", "de" to "Muschelweiß"),
            "#D8BFD8" to mapOf("en" to "Thistle", "de" to "Distel"),
            "#E6E6FA" to mapOf("en" to "Lavender", "de" to "Lavendel"),
            "#AFEEEE" to mapOf("en" to "Pale Turquoise", "de" to "Blass-Türkis"),
            "#DB7093" to mapOf("en" to "Pale Violet Red", "de" to "Blassviolett-Rot"),

            "#FFEFD5" to mapOf("en" to "Papaya Whip", "de" to "Papaya-Puder"),
            "#FFD700" to mapOf("en" to "Sun Yellow", "de" to "Sonnen-Gelb"),
            "#FFDEAD" to mapOf("en" to "Navajo White", "de" to "Navajo-Weiß"),
            "#E0B0FF" to mapOf("en" to "Mauve", "de" to "Malve"),
            "#98FB98" to mapOf("en" to "Pale Green", "de" to "Blassgrün"),
            "#AFB42B" to mapOf("en" to "Limeade", "de" to "Limettenade"),
            "#CD853F" to mapOf("en" to "Peru", "de" to "Peru Braun"),
            "#FFC3A0" to mapOf("en" to "Peach Orange", "de" to "Pfirsich-Orange"),
            "#B0E0E6" to mapOf("en" to "Powder Blue", "de" to "Puderblau")
        )
    }
}